on:
  pull_request:
    paths:
      - 'files/**'
      - '!files/local.txt'

jobs:
  hello:
    if: startsWith(github.head_ref, 'beta/') && !startsWith(github.head_ref, 'beta/daily_')
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello"
